# Base file that defines the canonical configuration for all services
# See override and production files for environment specific additions
# Further reading: https://docs.docker.com/compose/extends/#multiple-compose-files

version: "3"

services:
  webproxy:
    container_name: caddy
    read_only: true
    image: abiosoft/caddy:1.0.3-no-stats
    depends_on:
      - application
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./webproxy/Caddyfile_development:/etc/Caddyfile:ro
      - ./webproxy/certificates/:/etc/caddycerts
    environment:
      - CADDYPATH=/etc/caddycerts
      - ACME_AGREE=true
    networks:
      - public
      - private
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
  application:
    container_name: fileshelter
    read_only: true
    image: fileshelter
    build:
      context: ./application
      dockerfile: Dockerfile
    expose:
      - "5091"
    volumes:
      - ./application/uploads/:/var/fileshelter/
      - ./application/fileshelter.conf:/etc/fileshelter.conf:ro
      # - ./application/approot/messages.xml:/usr/share/fileshelter/approot/messages.xml:ro
      # - ./application/approot/templates.xml:/usr/share/fileshelter/approot/templates.xml:ro
      # - ./application/docroot/fileshelter.css:/usr/share/fileshelter/docroot/css/fileshelter.css:ro
      # - ./application/docroot/favicon.ico:/usr/share/fileshelter/docroot/favicon.ico:ro
    networks:
      - private
    cap_drop:
      - ALL

networks:
  public:
  private:
